export type PossibleTypesResultData = {
  possibleTypes: {
    Node: [
      'Shop',
      'Currency',
      'Role',
      'Group',
      'Account',
      'Tag',
      'NavigationTree',
      'NavigationItem',
      'HydraClient',
      'AddressValidationRule',
      'Template',
      'Invitation',
      'CatalogItemProduct',
      'CatalogProduct',
      'CatalogProductVariant',
      'Cart',
      'FulfillmentGroup',
      'FulfillmentMethod',
      'CartItem',
      'AppliedSurcharge',
      'Order',
      'OrderFulfillmentGroup',
      'OrderItem',
      'Payment',
      'Refund',
      'Surcharge',
      'FlatRateFulfillmentMethod',
      'FlatRateFulfillmentRestriction',
      'HomePageAsset',
      'Page',
      'SubscriptionPlan',
      'CatalogItemContent',
      'Catalog'
    ]
    NodeEdge: [
      'RoleEdge',
      'GroupEdge',
      'TagEdge',
      'ShopEdge',
      'AddressValidationRuleEdge',
      'AccountEdge',
      'InvitationEdge',
      'CartItemEdge',
      'OrderItemEdge',
      'OrderEdge',
      'OrdersByAccountIdEdge',
      'NavigationItemEdge',
      'HomePageAssetEdge',
      'PageEdge',
      'HydraClientEdge'
    ]
    Deletable: [
      'Tag',
      'HydraClient',
      'HomePageAsset',
      'Page',
      'SubscriptionPlan'
    ]
    CatalogItem: ['CatalogItemProduct', 'CatalogItemContent']
    CatalogProductOrVariant: ['CatalogProduct', 'CatalogProductVariant']
    OrderFulfillmentGroupData: ['ShippingOrderFulfillmentGroupData']
    PaymentData: [
      'FakeData',
      'StripeCardPaymentData',
      'ExampleIOUPaymentData',
      'EpaycoCreditPaymentData',
      'EpaycoDebitPaymentData',
      'EpaycoCashPaymentData',
      'NequiQRCodePaymentData',
      'BitpayPaymentData'
    ]
    PaymentMethodData: ['FakeData', 'ExampleIOUPaymentMethodData']
  }
}
const result: PossibleTypesResultData = {
  possibleTypes: {
    Node: [
      'Shop',
      'Currency',
      'Role',
      'Group',
      'Account',
      'Tag',
      'NavigationTree',
      'NavigationItem',
      'HydraClient',
      'AddressValidationRule',
      'Template',
      'Invitation',
      'CatalogItemProduct',
      'CatalogProduct',
      'CatalogProductVariant',
      'Cart',
      'FulfillmentGroup',
      'FulfillmentMethod',
      'CartItem',
      'AppliedSurcharge',
      'Order',
      'OrderFulfillmentGroup',
      'OrderItem',
      'Payment',
      'Refund',
      'Surcharge',
      'FlatRateFulfillmentMethod',
      'FlatRateFulfillmentRestriction',
      'HomePageAsset',
      'Page',
      'SubscriptionPlan',
      'CatalogItemContent',
      'Catalog',
    ],
    NodeEdge: [
      'RoleEdge',
      'GroupEdge',
      'TagEdge',
      'ShopEdge',
      'AddressValidationRuleEdge',
      'AccountEdge',
      'InvitationEdge',
      'CartItemEdge',
      'OrderItemEdge',
      'OrderEdge',
      'OrdersByAccountIdEdge',
      'NavigationItemEdge',
      'HomePageAssetEdge',
      'PageEdge',
      'HydraClientEdge',
    ],
    Deletable: [
      'Tag',
      'HydraClient',
      'HomePageAsset',
      'Page',
      'SubscriptionPlan',
    ],
    CatalogItem: ['CatalogItemProduct', 'CatalogItemContent'],
    CatalogProductOrVariant: ['CatalogProduct', 'CatalogProductVariant'],
    OrderFulfillmentGroupData: ['ShippingOrderFulfillmentGroupData'],
    PaymentData: [
      'FakeData',
      'StripeCardPaymentData',
      'ExampleIOUPaymentData',
      'EpaycoCreditPaymentData',
      'EpaycoDebitPaymentData',
      'EpaycoCashPaymentData',
      'NequiQRCodePaymentData',
      'BitpayPaymentData',
    ],
    PaymentMethodData: ['FakeData', 'ExampleIOUPaymentMethodData'],
  },
}
export default result
